<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInite70d96120b66527f4d795477b5375dc9
{
    public static $prefixLengthsPsr4 = array (
        'V' => 
        array (
            'Vimeo\\' => 6,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Vimeo\\' => 
        array (
            0 => __DIR__ . '/..' . '/vimeo/vimeo-api/src/Vimeo',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInite70d96120b66527f4d795477b5375dc9::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInite70d96120b66527f4d795477b5375dc9::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInite70d96120b66527f4d795477b5375dc9::$classMap;

        }, null, ClassLoader::class);
    }
}
